import eslint from '@eslint/js';
import globals from "globals";
import react from "eslint-plugin-react";
import tseslint from 'typescript-eslint';
import typescriptParser from '@typescript-eslint/parser';

export default [
  {
    ignores: ['**/node_modules', 'dist', 'webpack*'],
  },
  {
    settings: {
      react: {
        version: '18.3.1',
      },
    },
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}', 'tests/**/*.{ts,tsx}'],
    languageOptions: {parser: typescriptParser, ecmaVersion: 2022, sourceType: 'module'},
    rules: {
      // '@typescript-eslint/indent': ['error', 2],
      // '@typescript-eslint/no-shadow': ['error'],
      // 'async-await/space-after-async': 2,
      // 'async-await/space-after-await': 2,
      'array-element-newline': 'off',
      'arrow-parens': 'off',
      'capitalized-comments': 'off',
      'comma-dangle': ['error', 'always-multiline'],
      'comma-spacing': ['warn', {'before': false, 'after': true}],
      'consistent-return': 'error',
      'dot-location': 'off',
      'default-case': 'off',
      'function-call-argument-newline': 'off',
      'id-length': 'off',
      'implicit-arrow-linebreak': 'off',
      'indent': ['warn', 2, {'SwitchCase': 1, 'MemberExpression': 'off'}],
      'init-declarations': 'off',
      'key-spacing': ['warn', {}],
      'line-comment-position': 'off',
      'linebreak-style': ['error', 'unix'],
      'lines-around-comment': 'off',
      'max-classes-per-file': 'off',
      'max-depth': 'off',
      'max-len': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'multiline-comment-style': 'off',
      'multiline-ternary': 'off',
      'new-cap': 'off',
      'no-confusing-arrow': 'off',
      'no-console': ['warn'],
      'no-duplicate-imports': 'off',
      'no-empty': 'warn',
      'no-extra-parens': 'off',
      'no-inline-comments': 'off',
      'no-magic-numbers': ['error', {'ignore': [0, 1]}],
      'no-mixed-operators': 'off',
      'no-multi-assign': 'off',
      'no-multi-comp': 'off',
      'no-nested-ternary': 'off',
      'no-plusplus': 'off',
      'no-return-await': 'error',
      'no-sequences': 'off',
      'no-shadow': 'off',
      'no-ternary': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': ['off'],
      'no-unused-vars': ['warn'],
      'no-use-before-define': 'off', // fucking react before use
      'no-warning-comments': 'off',
      'object-curly-spacing': 'off',
      'object-property-newline': 'off',
      'one-var': 'off',
      'padded-blocks': 'off',
      'prefer-destructuring': 'off',
      'quote-props': 'off',
      'quotes': ['error', 'single'],
      'require-await': 'error',
      'semi-style': 'off',
      'semi': ['error', 'always'],
      'sort-imports': ['error'],
      'sort-keys': 'off',
      'space-before-function-paren': 'off',
      'space-infix-ops': ['warn'],
    },
  },
  react.configs.flat.recommended,
  {
    files: ['src/**/*.{tsx}', 'tests/**/*.{tsx}'],
    plugins: {react},
    languageOptions: {
      parserOptions: {ecmaFeatures: {jsx: true}},
      globals: {
        ...globals.browser,
      }
    },
    rules: {
      // https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope
      'react/destructuring-assignment': 'error',
      'react/forbid-component-props': 'off',
      'react/forbid-prop-types': 'off',
      'react/function-component-definition': [1, {'namedComponents': 'arrow-function'}],
      'react/jsx-closing-bracket-location': 'off',
      'react/jsx-closing-tag-location': 'off',
      'react/jsx-filename-extension': [1, {'extensions': ['.tsx']}],
      'react/jsx-fragments': 'off',
      'react/jsx-handler-names': 'off',
      'react/jsx-indent': 'off',
      'react/jsx-indent-props': ['error', 2],
      'react/jsx-max-depth': 'off',
      'react/jsx-max-props-per-line': [1, {'when': 'multiline'}],
      'react/jsx-no-bind': 'off',
      'react/jsx-no-literals': 'off',
      'react/jsx-props-no-spreading': 'off',
      'react/jsx-sort-default-props': 'error',
      'react/jsx-sort-props': 'error',
      'react/jsx-wrap-multilines': 'off',
      'react/no-multi-comp': 'off',
      'react/no-set-state': 'error',
      'react/prefer-stateless-function': 'off',
      'react/prop-types': 'off',
      'react/require-default-props': 'off',
      'react/sort-prop-types': 'error',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      // https://stackoverflow.com/questions/63961803/eslint-says-all-enums-in-typescript-app-are-already-declared-in-the-upper-scope
    },
  },
];
